// MEVN-App/frontend/src/pages/Login.vue
<template>
  <div class="p-8 max-w-md mx-auto">
    <h2 class="text-2xl font-bold mb-4">Login</h2>
    <form @submit.prevent="login">
      <input v-model="email" type="email" placeholder="Email" class="border p-2 w-full mb-3" />
      <input v-model="password" type="password" placeholder="Password" class="border p-2 w-full mb-3" />
      <button type="submit" class="bg-green-500 text-white px-4 py-2">Login</button>
    </form>
    <p class="text-red-500 mt-3">{{ error }}</p>
  </div>
</template>

<script>
import API from "../services/api";

export default {
  data() {
    return {
      email: "",
      password: "",
      error: "",
    };
  },
  methods: {
    // logging in 
    async login() {
      try {
        // await the API call to login
        const res = await API.post("/auth/login", {
          email: this.email,
          password: this.password,
        });
        // get token and user role from response
        localStorage.setItem("token", res.data.token);
        if (res.data.user.role === "member") {
          this.$router.push("/donor");
        } else {
          this.$router.push("/beneficiary");
        }
      } catch (err) {
        this.error = err.response?.data?.msg || "Login failed";
      }
    },
  },
};
</script>

// MEAN-App/frontend/src/app/components/login/login.component.ts
// importing necessary modules and services (for angular component, api service, router, etc.)
import { Component } from '@angular/core';
import { ApiService } from '../../services/api.service';
import { Router } from '@angular/router';

// setting up the component with its selector and template
@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']

})

// exporting the LoginComponent class
export class LoginComponent {
  form = { email: '', password: '' };
  msg = '';

  constructor(private api: ApiService, private router: Router) {}

  // login method to authenticate user
  login() {
    this.api.login(this.form).subscribe({
      next: (res) => {
        // Save token and user
        localStorage.setItem('token', res.token);
        localStorage.setItem('user', JSON.stringify(res.user));
        this.msg = 'Login successful!';

        // Navigate by role
        if (res.user.role === 'member') {
          this.router.navigate(['/donor-dashboard']);
        } else {
          this.router.navigate(['/beneficiary-dashboard']);
        }
      },
      error: (err) => {
        this.msg = err.error?.msg || 'Invalid credentials';
      }
    });
  }
}

<div class="form-container">
  <h2>Login</h2>

  <div class="form-group">
    <input [(ngModel)]="form.email" placeholder="Email" />
  </div>

  <div class="form-group">
    <input [(ngModel)]="form.password" type="password" placeholder="Password" />
  </div>

  <button (click)="login()">Login</button>

  <p class="error">{{ msg }}</p>
</div>
