// MEAN-App/frontend/src/app/components/register/register.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
  form: any = { name: '', email: '', password: '', role: 'beneficiary' };
  msg = '';

  constructor(private http: HttpClient, private router: Router) {}

  register() {
    this.http.post<any>('http://localhost:5000/api/auth/register', this.form)
      .subscribe({
        next: (res) => {
          // save token + user data in localStorage
          localStorage.setItem('token', res.token);
          localStorage.setItem('user', JSON.stringify(res.user));

          // redirect based on role
          if (res.user.role === 'beneficiary') {
            this.router.navigate(['/beneficiary-dashboard']);
          } else if (res.user.role === 'member') {
            this.router.navigate(['/donor-dashboard']);
          }

        },
        error: (err) => {
          this.msg = err.error.msg || 'Registration failed';
        }
      });
  }
}

<div class="form-container">
  <h2>Register</h2>

  <div class="form-group">
    <input [(ngModel)]="form.name" placeholder="Name" />
  </div>

  <div class="form-group">
    <input [(ngModel)]="form.email" placeholder="Email" />
  </div>

  <div class="form-group">
    <input [(ngModel)]="form.password" type="password" placeholder="Password" />
  </div>

  <div class="form-group">
    <select [(ngModel)]="form.role">
      <option value="beneficiary">Beneficiary</option>
      <option value="member">Member</option>
    </select>
  </div>

  <button (click)="register()">Register</button>

  <p class="error">{{ msg }}</p>
</div>

// MEVN-App/frontend/src/pages/Register.vue
<template>
  <div class="p-8 max-w-md mx-auto">
    <h2 class="text-2xl font-bold mb-4">Register</h2>
    <form @submit.prevent="register">
      <input v-model="name" placeholder="Name" class="border p-2 w-full mb-3" />
      <input v-model="email" type="email" placeholder="Email" class="border p-2 w-full mb-3" />
      <input v-model="password" type="password" placeholder="Password" class="border p-2 w-full mb-3" />
      <select v-model="role" class="border p-2 w-full mb-3">
        <option value="member">Member</option>
        <option value="beneficiary">Beneficiary</option>
      </select>
      <button type="submit" class="bg-blue-500 text-white px-4 py-2">Register</button>
    </form>
    <p class="text-red-500 mt-3">{{ error }}</p>
  </div>
</template>

<script>
import API from "../services/api";

export default {
  data() {
    return {
      name: "",
      email: "",
      password: "",
      role: "beneficiary",
      error: "",
    };
  },
  methods: {
    // method to register user
    async register() {
      try {
        const res = await API.post("/auth/register", {
          name: this.name,
          email: this.email,
          password: this.password,
          role: this.role,
        });
        // sending token to local storage and redirecting based on role
        localStorage.setItem("token", res.data.token);
        if (this.role === "member") {
          this.$router.push("/donor");
        } else {
          this.$router.push("/beneficiary");
        }
      } catch (err) {
        this.error = err.response?.data?.msg || "Error registering";
      }
    },
  },
};
</script>
